[package]
name = "matching-engine-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }
arbitrary = { version = "1", features = ["derive"] }
bumpalo = { version = "3", features = ["collections"] }

[dependencies.matching-engine]
path = ".."

# Keep fuzz out of the workspace so normal builds ignore it
[workspace]

[[bin]]
name = "engine_fuzz"
path = "fuzz_targets/engine_fuzz.rs"
test = false
doc = false
