[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
ouch-gateway = { path = "../ouch-gateway" }
rest-gateway = { path = "../rest-gateway" }
matching-engine = { path = "../matching-engine" }
axum = "0.8.9"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
metrics = ["ouch-gateway/metrics"]